index:
   path: /
   controller: App\Controller\DefaultController::index

rubik:
   path: /rubik
   controller: App\Controller\RubiksController::index

about:
   path: /about
   controller: App\Controller\AboutController::index